name: CI

on:
  push:
  pull_request:

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run demo conversion
        run: |
          python ascii_art.py --demo -w 80
      - name: Verify outputs exist
        run: |
          test -f out/demo_80.txt
          test -f out/demo_80.png
